<?php
	function theme_locals($label) {
		$locals = array(
			//general
			'no' => __('No', HS_CURRENT_THEME),
			'yes' => __('Yes', HS_CURRENT_THEME),
			'slow_speed' => __('Slow', HS_CURRENT_THEME),
			'normal_speed' => __('Normal', HS_CURRENT_THEME),
			'fast_speed' => __('Fast', HS_CURRENT_THEME),
			'normal_size' => __('Normal size', HS_CURRENT_THEME),
			'large_size' => __('Large size', HS_CURRENT_THEME),
			'font_size' => __('Font Size', HS_CURRENT_THEME),
			'lineheight' => __('Lineheight', HS_CURRENT_THEME),
			'font_face' => __('Font Face', HS_CURRENT_THEME),
			'character_sets' => __('Character Sets', HS_CURRENT_THEME),
			'font_style' => __('Font Style', HS_CURRENT_THEME),
			'color' => __('Color', HS_CURRENT_THEME),
			'import' => __('Import', HS_CURRENT_THEME),
			'export' => __('Export', HS_CURRENT_THEME),
			'done' => __('Done', HS_CURRENT_THEME),
			'error' => __('Error', HS_CURRENT_THEME),
			'success' => __('success', HS_CURRENT_THEME),
			'upload' => __('Upload', HS_CURRENT_THEME),
			'try_again' => __('try again', HS_CURRENT_THEME),
			'finish' => __('Finish', HS_CURRENT_THEME),
			'skip' => __('Skip this step', HS_CURRENT_THEME),
			'install_next' => __('next', HS_CURRENT_THEME),
			'none' => __('None', HS_CURRENT_THEME),
			'date' => __('Date', HS_CURRENT_THEME),
			'title' => __('Title', HS_CURRENT_THEME),
			'info' => __('Info', HS_CURRENT_THEME),
			'rand' => __('Random', HS_CURRENT_THEME),
			'comment_count' => __('Comment count', HS_CURRENT_THEME),
			'enable_lightbox' => __('Enable Lightbox', HS_CURRENT_THEME),
			'enable_lightbox_desc' => __('Check this to enable the lightbox.', HS_CURRENT_THEME),
			'permalink_to' => __('Permalink', HS_CURRENT_THEME),
			'read_more' => __('Read more', HS_CURRENT_THEME),
			'view_all' => __('View all', HS_CURRENT_THEME),
			'width' => __('Width', HS_CURRENT_THEME),
			'height' => __('Height', HS_CURRENT_THEME),
			'excerpt_length' => __('Excerpt length (words):', HS_CURRENT_THEME),
			'link_text' => __('Link Text:', HS_CURRENT_THEME),
			'link_url' => __('Link URL', HS_CURRENT_THEME),
			'standard' => __('Standard', HS_CURRENT_THEME),
			'aside' => __('Aside', HS_CURRENT_THEME),
			'quote' => __('Quote', HS_CURRENT_THEME),
			'link' => __('Link', HS_CURRENT_THEME),
			'image' => __('Image', HS_CURRENT_THEME),
			'gallery' => __('Gallery', HS_CURRENT_THEME),
			'audio' => __('Audio', HS_CURRENT_THEME),
			'video' => __('Video', HS_CURRENT_THEME),
			'categories' => __('Categories', HS_CURRENT_THEME),
			'tags' => __('Tags', HS_CURRENT_THEME),
			'show_all' => __('Show All', HS_CURRENT_THEME),
			'search' => __('search', HS_CURRENT_THEME),
			'go' => __('Go', HS_CURRENT_THEME),
			'prev_post' => __('&laquo; Previous post', HS_CURRENT_THEME),
			'next_post' => __('Next Post &raquo;', HS_CURRENT_THEME),
			'url' => __('URL', HS_CURRENT_THEME),
			'url_1' => __('URL #1', HS_CURRENT_THEME),
			'url_2' => __('URL #2', HS_CURRENT_THEME),
			'uncategorized' => __('Uncategorized', HS_CURRENT_THEME),
			'last' => __('Last', HS_CURRENT_THEME),
			'first' => __('First', HS_CURRENT_THEME),
			'delete' => __('Delete', HS_CURRENT_THEME),
			'share_on' => __('Share on:', HS_CURRENT_THEME),
			//Output Audio
			'prev' => __('Previous', HS_CURRENT_THEME),
			'next' => __('Next', HS_CURRENT_THEME),
			'play' => __('Play', HS_CURRENT_THEME),
			'pause' => __('Pause', HS_CURRENT_THEME),
			'stop' => __('Stop', HS_CURRENT_THEME),
			'mute' => __('Mute', HS_CURRENT_THEME),
			'unmute' => __('Unmute', HS_CURRENT_THEME),
			'update_required' => __("<span>Update Required. </span>To play the media you will need to either update your browser to a recent version or update your <a href='http://get.adobe.com/flashplayer/' target='_blank'>Flash plugin</a>.", HS_CURRENT_THEME),
			
			//Theme options
			'theme_options' => __('Options', HS_CURRENT_THEME),
			'customize' => __('Customize', HS_CURRENT_THEME),
			'support' => __('Support', HS_CURRENT_THEME),
			'documentation' => __('Documentation', HS_CURRENT_THEME),
			'save_options' => __('Save Options', HS_CURRENT_THEME),
			'restore_defaults' => __('Restore Defaults', HS_CURRENT_THEME),
			'restore_defaults_desc' => __('Click OK to reset. Any theme settings will be lost!', HS_CURRENT_THEME),
			
			//general options
			'general' => __('General', HS_CURRENT_THEME),
			'body_name' => __('Body styling', HS_CURRENT_THEME),
			'body_desc' => __('Change the background style', HS_CURRENT_THEME),
			'background_image' => __('Background Image', HS_CURRENT_THEME),
			'background_color' => __('Background Color', HS_CURRENT_THEME),
			'header_name' => __('Header background color', HS_CURRENT_THEME),
			'header_desc' => __('Change the header background color', HS_CURRENT_THEME),
			'buttons_name' => __('Link color', HS_CURRENT_THEME),
			'buttons_desc' => __('Change the color of link', HS_CURRENT_THEME),
			'links_color_hover' => __('Link color hover', HS_CURRENT_THEME),
			'links_color_hover_desc' => __('Change the color of link hover state', HS_CURRENT_THEME),
			'body_text_name' => __('Body Text', HS_CURRENT_THEME),
			'body_text_desc' => __("Choose your prefered font for body text. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href='http://www.google.com/webfonts'>Google Web Fonts</a> library.</em>", HS_CURRENT_THEME),
			'h1_name' => __('H1 Heading', HS_CURRENT_THEME),
			'h1_desc' => __("Choose your prefered font for H1 heading and titles. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href='http://www.google.com/webfonts'>Google Web Fonts</a> library.</em>", HS_CURRENT_THEME),
			'h2_name' => __('H2 Heading', HS_CURRENT_THEME),
			'h2_desc' => __("Choose your prefered font for H2 heading and titles. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href='http://www.google.com/webfonts'>Google Web Fonts</a> library.</em>", HS_CURRENT_THEME),
			'h3_name' => __('H3 Heading', HS_CURRENT_THEME),
			'h3_desc' => __("Choose your prefered font for H3 heading and titles. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href='http://www.google.com/webfonts'>Google Web Fonts</a> library.</em>", HS_CURRENT_THEME),
			'h4_name' => __('H4 Heading', HS_CURRENT_THEME),
			'h4_desc' => __("Choose your prefered font for H4 heading and titles. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href='http://www.google.com/webfonts'>Google Web Fonts</a> library.</em>", HS_CURRENT_THEME),
			'h5_name' => __('H5 Heading', HS_CURRENT_THEME),
			'h5_desc' => __("Choose your prefered font for H5 heading and titles. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href='http://www.google.com/webfonts'>Google Web Fonts</a> library.</em>", HS_CURRENT_THEME),
			'h6_name' => __('H6 Heading', HS_CURRENT_THEME),
			'h6_desc' => __("Choose your prefered font for H6 heading and titles. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href='http://www.google.com/webfonts'>Google Web Fonts</a> library.</em>", HS_CURRENT_THEME),
			'search_name' => __('Display search box?', HS_CURRENT_THEME),
			'search_desc' => __('Display search box in the header?', HS_CURRENT_THEME),
			'breadcrumbs_name' => __('Display breadcrumbs?', HS_CURRENT_THEME),
			'breadcrumbs_desc' => __('Display breadcrumbs in the page?', HS_CURRENT_THEME),
			'css_name' => __('Custom CSS', HS_CURRENT_THEME),
			'css_desc' => __('Want to add any custom CSS code? Put in here, and the rest is taken care of. This overrides any other stylesheets. eg: a.button{color:green}', HS_CURRENT_THEME),
			'search_term' => __('Enter your search term...', HS_CURRENT_THEME),

			//Logo & Favicon options
			'logo' => __('Logo', HS_CURRENT_THEME),
			'logo_favicon' => __('Logo & Favicon', HS_CURRENT_THEME),
			'logo_name' => __('What kind of logo?', HS_CURRENT_THEME),
			'logo_desc' => __('Select whether you want your main logo to be an image or text. If you select "image" you can put in the image url in the next option, and if you select "text" your Site Title will be shown instead.', HS_CURRENT_THEME),
			'image_logo' => __('Image Logo', HS_CURRENT_THEME),
			'text_logo' => __('Text Logo', HS_CURRENT_THEME),
			'logo_t_name' => __('Logo Typography', HS_CURRENT_THEME),
			'logo_t_desc' => __("Choose your prefered font for menu. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href='http://www.google.com/webfonts'>Google Web Fonts</a> library.</em>", HS_CURRENT_THEME),
			'logo_image_path' => __('Logo Image Path', HS_CURRENT_THEME),
			'logo_image_path_desc' => __('Click Upload or Enter the direct path to your <strong>logo image</strong>. For example <em>http://your_website_url_here/wp-content/themes/themeXXXX/images/logo.png</em>', HS_CURRENT_THEME),
			'favicon_name' => __('Favicon', HS_CURRENT_THEME),
			'favicon_desc' => __('Click Upload or Enter the direct path to your <strong>favicon</strong>. For example <em>http://your_website_url_here/wp-content/themes/themeXXXX/favicon.ico</em>', HS_CURRENT_THEME),
			
			//Navigation options
			'navigation' => __('Navigation', HS_CURRENT_THEME),
			'menu_t_name' => __('Menu Typography', HS_CURRENT_THEME),
			'menu_t_desc' => __("Choose your prefered font for menu. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href='http://www.google.com/webfonts'>Google Web Fonts</a> library.</em>", HS_CURRENT_THEME),
			'delay_name' => __('Delay', HS_CURRENT_THEME),
			'delay_desc' => __('Miliseconds delay on mouseout.', HS_CURRENT_THEME),
			'fade_name' => __('Fade-in animation', HS_CURRENT_THEME),
			'fade_desc' => __('Fade-in animation.', HS_CURRENT_THEME),
			'slide_name' => __('Slide-down animation.', HS_CURRENT_THEME),
			'slide_desc' => __('Slide-down animation.', HS_CURRENT_THEME),
			'enable fade-in animation' => __('Enable fade-in animation', HS_CURRENT_THEME),
			'disable fade-in animation' => __('Disable fade-in animation', HS_CURRENT_THEME),
			'enable slide-down animation' => __('Enable slide-down animation', HS_CURRENT_THEME),
			'disable slide-down animation' => __('Disable slide-down animation', HS_CURRENT_THEME),
			'speed_name' => __('Speed', HS_CURRENT_THEME),
			'speed_desc' => __('Animation speed.', HS_CURRENT_THEME),
			'arrows_name' => __('Arrows markup.', HS_CURRENT_THEME),
			'arrows_desc' => __('Do you want to generate arrow mark-up?', HS_CURRENT_THEME),
			'mobile_menu_name' => __('Mobile menu label.', HS_CURRENT_THEME),
			'mobile_menu_desc' => __('This text is visible in mobile select menu.', HS_CURRENT_THEME),
			'mobile_menu_std' => __('Navigate to...', HS_CURRENT_THEME),
			
			//Slider Settings options
			'slider' => __('Slider Settings', HS_CURRENT_THEME),
			'slider_name' => __('Slider', HS_CURRENT_THEME),
			'slider_type_name' => __('The type of slider', HS_CURRENT_THEME),
			'slider_type_desc' => __('You can choose the type of slider that suits you best.', HS_CURRENT_THEME),
			'slider_off' => __('Disable slider', HS_CURRENT_THEME),
			'camera_slider' => __('Slideshow', HS_CURRENT_THEME),
			'accordion_slider' => __('Slides', HS_CURRENT_THEME),
			'effect_name' => __('Sliding effect', HS_CURRENT_THEME),
			'effect_desc' => __('Select your animation type.', HS_CURRENT_THEME),
			'random' => __('random', HS_CURRENT_THEME),
			'simpleFade' => __('simpleFade', HS_CURRENT_THEME),
			'curtainTopLeft' => __('curtainTopLeft', HS_CURRENT_THEME),
			'curtainTopRight' => __('curtainTopRight', HS_CURRENT_THEME),
			'curtainBottomLeft' => __('curtainBottomLeft', HS_CURRENT_THEME),
			'curtainBottomRight' => __('curtainBottomRight', HS_CURRENT_THEME),
			'curtainSliceLeft' => __('curtainSliceLeft', HS_CURRENT_THEME),
			'curtainSliceRight' => __('curtainSliceRight', HS_CURRENT_THEME),
			'blindCurtainTopLeft' => __('blindCurtainTopLeft', HS_CURRENT_THEME),
			'blindCurtainTopRight' => __('blindCurtainTopRight', HS_CURRENT_THEME),
			'blindCurtainBottomLeft' => __('blindCurtainBottomLeft', HS_CURRENT_THEME),
			'blindCurtainBottomRight' => __('blindCurtainBottomRight', HS_CURRENT_THEME),
			'blindCurtainSliceBottom' => __('blindCurtainSliceBottom', HS_CURRENT_THEME),
			'blindCurtainSliceTop' => __('blindCurtainSliceTop', HS_CURRENT_THEME),
			'stampede' => __('stampede', HS_CURRENT_THEME),
			'mosaic' => __('mosaic', HS_CURRENT_THEME),
			'mosaicReverse' => __('mosaicReverse', HS_CURRENT_THEME),
			'mosaicRandom' => __('mosaicRandom', HS_CURRENT_THEME),
			'mosaicSpiral' => __('mosaicSpiral', HS_CURRENT_THEME),
			'mosaicSpiralReverse' => __('mosaicSpiralReverse', HS_CURRENT_THEME),
			'topLeftBottomRight' => __('topLeftBottomRight', HS_CURRENT_THEME),
			'bottomRightTopLeft' => __('bottomRightTopLeft', HS_CURRENT_THEME),
			'bottomLeftTopRight' => __('bottomLeftTopRight', HS_CURRENT_THEME),
			'columns_name' => __('Number of columns', HS_CURRENT_THEME),
			'columns_desc' => __('Number of columns', HS_CURRENT_THEME),
			'rows_name' => __('Number of rows', HS_CURRENT_THEME),
			'rows_desc' => __('Number of rows', HS_CURRENT_THEME),
			'banner_name' => __('Banner effect', HS_CURRENT_THEME),
			'moveFromLeft' => __('moveFromLeft', HS_CURRENT_THEME),
			'moveFromRight' => __('moveFromRight', HS_CURRENT_THEME),
			'moveFromTop' => __('moveFromTop', HS_CURRENT_THEME),
			'moveFromBottom' => __('moveFromBottom', HS_CURRENT_THEME),
			'fadeIn' => __('fadeIn', HS_CURRENT_THEME),
			'fadeFromLeft' => __('fadeFromLeft', HS_CURRENT_THEME),
			'fadeFromRight' => __('fadeFromRight', HS_CURRENT_THEME),
			'fadeFromTop' => __('fadeFromTop', HS_CURRENT_THEME),
			'fadeFromBottom' => __('fadeFromBottom', HS_CURRENT_THEME),
			'banner_desc' => __('Select your banner animation type.', HS_CURRENT_THEME),
			'pause_name' => __('Pause time', HS_CURRENT_THEME),
			'pause_desc' => __('Pause time (ms).', HS_CURRENT_THEME),
			'animation_name' => __('Animation speed', HS_CURRENT_THEME),
			'animation_desc' => __('Animation speed (ms)', HS_CURRENT_THEME),
			'slideshow_name' => __('Slideshow', HS_CURRENT_THEME),
			'slideshow_desc' => __('Animate slider automatically?', HS_CURRENT_THEME),
			'thumbnails_name' => __('Thumbnails', HS_CURRENT_THEME),
			'thumbnails_desc' => __('Display thumbnails?', HS_CURRENT_THEME),
			'pagination_name' => __('Pagination', HS_CURRENT_THEME),
			'pagination_desc' => __('Display pagination?', HS_CURRENT_THEME),
			'navigation_name' => __('Next & Prev navigation', HS_CURRENT_THEME),
			'navigation_desc' => __('Display next & prev navigation?', HS_CURRENT_THEME),
			'hover_name' => __('Display next & prev navigation only on hover?', HS_CURRENT_THEME),
			'hover_desc' => __('If true the navigation button (prev, next and play/stop buttons) will be visible on hover state only, if false they will be visible always', HS_CURRENT_THEME),
			'button_name' => __('Play/Pause button', HS_CURRENT_THEME),
			'button_desc' => __('Display Play/Pause button?', HS_CURRENT_THEME),
			'loader_name' => __('Loader', HS_CURRENT_THEME),
			'loader_desc' => __('Slider loader', HS_CURRENT_THEME),
			'pie' => __('Pie', HS_CURRENT_THEME),
			'bar' => __('Bar', HS_CURRENT_THEME),

			//Accardion Slider Settings options
			'show_post_name' => __('Slides to display', HS_CURRENT_THEME),
			'show_post_desc' => __('Select the slides that you want to be displayed on slider. If no slide is selected, all slides will be displayed.', HS_CURRENT_THEME),
			'hover_pause_name' => __('Pause on mouseover', HS_CURRENT_THEME),
			'hover_pause_desc' => __('The auto play will pause when you mouse over the slider.', HS_CURRENT_THEME),
			'easing_name' => __('Animation slowdown', HS_CURRENT_THEME),
			'easing_desc' => __('You can choose different types of animation slowdown for transition of slides.', HS_CURRENT_THEME),
			'trigger_name' => __('Mouse events for transition of slides', HS_CURRENT_THEME),
			'trigger_desc' => __('You can choose different types of mouse events for transition of slides.', HS_CURRENT_THEME),
			'click' => __('Click', HS_CURRENT_THEME),
			'mouseover' => __('Mouseover', HS_CURRENT_THEME),
			'dblclick' => __('Double click', HS_CURRENT_THEME),
			'starting_slide_name' => __('Active slide', HS_CURRENT_THEME),
			'starting_slide_desc' => __('Set the number of slide that will be active by default. If the value is 0, all slides will be of the same width when page loads.', HS_CURRENT_THEME),
			'linear' => __('linear', HS_CURRENT_THEME),
			'easeInSine' => __('easeInSine', HS_CURRENT_THEME),
			'easeOutSine' => __('easeOutSine', HS_CURRENT_THEME),
			'easeInOutSine' => __('easeInOutSine', HS_CURRENT_THEME),
			'easeInQuad' => __('easeInQuad', HS_CURRENT_THEME),
			'easeOutQuad' => __('easeOutQuad', HS_CURRENT_THEME),
			'easeInOutQuad' => __('easeInOutQuad', HS_CURRENT_THEME),
			'easeInCubic' => __('easeInCubic', HS_CURRENT_THEME),
			'easeOutCubic' => __('easeOutCubic', HS_CURRENT_THEME),
			'easeInOutCubic' => __('easeInOutCubic', HS_CURRENT_THEME),
			'easeInQuart' => __('easeInQuart', HS_CURRENT_THEME),
			'easeOutQuart' => __('easeOutQuart', HS_CURRENT_THEME),
			'easeInOutQuart' => __('easeInOutQuart', HS_CURRENT_THEME),
			'easeInQuint' => __('easeInQuint', HS_CURRENT_THEME),
			'easeOutQuint' => __('easeOutQuint', HS_CURRENT_THEME),
			'easeInOutQuint' => __('easeInOutQuint', HS_CURRENT_THEME),
			'easeInExpo' => __('easeInExpo', HS_CURRENT_THEME),
			'easeOutExpo' => __('easeOutExpo', HS_CURRENT_THEME),
			'easeInOutExpo' => __('easeInOutExpo', HS_CURRENT_THEME),
			'easeInCirc' => __('easeInCirc', HS_CURRENT_THEME),
			'easeOutCirc' => __('easeOutCirc', HS_CURRENT_THEME),
			'easeInOutCirc' => __('easeInOutCirc', HS_CURRENT_THEME),
			'easeInBack' => __('easeInBack', HS_CURRENT_THEME),
			'easeOutBack' => __('easeOutBack', HS_CURRENT_THEME),
			'easeInOutBack' => __('easeInOutBack', HS_CURRENT_THEME),
			'easeInElastic' => __('easeInElastic', HS_CURRENT_THEME),
			'easeOutElastic' => __('easeOutElastic', HS_CURRENT_THEME),
			'easeInOutElastic' => __('easeInOutElastic', HS_CURRENT_THEME),
			'easeInBounce' => __('easeInBounce', HS_CURRENT_THEME),
			'easeOutBounce' => __('easeOutBounce', HS_CURRENT_THEME),
			'easeInOutBounce' => __('easeInOutBounce', HS_CURRENT_THEME),

			//Blog options
			'blog' => __('Blog', HS_CURRENT_THEME),
			'blog_name' => __('Blog Title', HS_CURRENT_THEME),
			'blog_desc' => __('Enter Your Blog Title used on Blog page.', HS_CURRENT_THEME),
			'posts_name' => __('Related Posts Title', HS_CURRENT_THEME),
			'posts_desc' => __('Enter Your Title used on Single Post page for related posts.', HS_CURRENT_THEME),
			'posts_std' => __('Related Posts', HS_CURRENT_THEME),
			'sidebar_name' => __('Sidebar position', HS_CURRENT_THEME),
			'sidebar_desc' => __('Choose sidebar position.', HS_CURRENT_THEME),
			'image_size_name' => __('Blog image size', HS_CURRENT_THEME),
			'image_size_desc' => __('Featured image size on the blog.', HS_CURRENT_THEME),
			'load_image_name' => __('Should images be uploaded on page scroll?', HS_CURRENT_THEME),
			'load_image_desc' => __('You can enable images load only as you scroll down the page. Otherwise images will load all at once.', HS_CURRENT_THEME),
			'single_post_image_name' => __('Single post image size', HS_CURRENT_THEME),
			'single_post_image_desc' => __('Featured image size on the single page.', HS_CURRENT_THEME),
			'meta_name' => __('View meta of the blog.', HS_CURRENT_THEME),
			'meta_desc' => __('Select meta block type which will be displayed on blog and post pages.', HS_CURRENT_THEME),
			'excerpt_name' => __('Enable excerpt for blog posts?', HS_CURRENT_THEME),
			'excerpt_desc' => __('Enable or Disable excerpt for blog posts.', HS_CURRENT_THEME),
			'hide' => __('Do not show.', HS_CURRENT_THEME),
			'line' => __('Lines.', HS_CURRENT_THEME),
			'grid' => __('Columns.', HS_CURRENT_THEME),
			'icon' => __('Icons.', HS_CURRENT_THEME),
			'post_date_name' => __('Post publication date.', HS_CURRENT_THEME),
			'post_date_desc' => __('Should the post publication date be displayed?', HS_CURRENT_THEME),
			'post_author_name' => __('Author of the post.', HS_CURRENT_THEME),
			'post_author_desc' => __('Display the author of the post?', HS_CURRENT_THEME),
			'post_permalink_name' => __('Direct link to the post.', HS_CURRENT_THEME),
			'post_permalink_desc' => __('Should the direct link to the post be displayed? ', HS_CURRENT_THEME),
			'post_category_name' => __('Post categories.', HS_CURRENT_THEME),
			'post_category_desc' => __('Should the post categories be displayed?', HS_CURRENT_THEME),
			'post_tag_name' => __('Tags be displayed.', HS_CURRENT_THEME),
			'post_tag_desc' => __('Should the tags be displayed?', HS_CURRENT_THEME),
			'post_comment_name' => __('Number of comments.', HS_CURRENT_THEME),
			'post_comment_desc' => __('Should the number of comments be displayed?', HS_CURRENT_THEME),
			'post_views_name' => __('Number of view.', HS_CURRENT_THEME),
			'post_views_desc' => __('Should the number of view be displayed?', HS_CURRENT_THEME),
			'post_like_name' => __('Number of likes.', HS_CURRENT_THEME),
			'post_like_desc' => __('Should the number of likes be displayed?', HS_CURRENT_THEME),
			'post_dislike_name' => __('Number of dislikes.', HS_CURRENT_THEME),
			'post_dislike_desc' => __('Should the number of dislikes be displayed?', HS_CURRENT_THEME),
			//'' => __('', HS_CURRENT_THEME),
			
			//Gallery options
			'gallery' => __('Gallery', HS_CURRENT_THEME),
			'galcategories' => __('Gallery categories', HS_CURRENT_THEME),
			'gallery_categorie' => __('Gallery categorie', HS_CURRENT_THEME),
			'view_picture' => __('View Picture', HS_CURRENT_THEME),
			
			//Portfolio options
			'portfolio' => __('Portfolio', HS_CURRENT_THEME),
			'filter_name' => __('Filter', HS_CURRENT_THEME),
			'filter_desc' => __('Portfolio filter.', HS_CURRENT_THEME),
			'by_category' => __('By category', HS_CURRENT_THEME),
			'by_tags' => __('By tags', HS_CURRENT_THEME),
			'both' => __('Both (by category and tags)', HS_CURRENT_THEME),
			'show_title_name' => __('Show title?', HS_CURRENT_THEME),
			'show_title_desc' => __('Enable or Disable title for portfolio posts.', HS_CURRENT_THEME),
			'show_excerpt_name' => __('Show excerpt?', HS_CURRENT_THEME),
			'show_excerpt_desc' => __('Enable or Disable excerpt for portfolio posts.', HS_CURRENT_THEME),
			'excerpt_words_name' => __('Excerpt words', HS_CURRENT_THEME),
			'excerpt_words_desc' => __('Excerpt length (words).', HS_CURRENT_THEME),
			'show_button_name' => __('Show button?', HS_CURRENT_THEME),
			'show_button_desc' => __('Enable or Disable button for portfolio posts.', HS_CURRENT_THEME),
			'show_meta_name' => __('Show portfolio meta?', HS_CURRENT_THEME),
			'show_meta_desc' => __('Enable or Disable meta for single portfolio posts.', HS_CURRENT_THEME),
			'folio_enable_lightbox_desc' => __('Enable or Disable lightbox for portfolio posts.', HS_CURRENT_THEME),
			'layout_name' => __('Layout', HS_CURRENT_THEME),
			'layout_desc' => __('Portfolio has different layout modes. You can set and change the layout mode via this option.', HS_CURRENT_THEME),
			'fit_rows' => __('Fit rows', HS_CURRENT_THEME),
			'masonry' => __('Masonry', HS_CURRENT_THEME),
			'portfolio_2_name' => __('Portfolio 2 columns items amount', HS_CURRENT_THEME),
			'portfolio_2_desc' => __('Portfolio items amount for Portfolio 2 columns template.', HS_CURRENT_THEME),
			'portfolio_3_name' => __('Portfolio 3 columns items amount', HS_CURRENT_THEME),
			'portfolio_3_desc' => __('Portfolio items amount for Portfolio 3 columns template.', HS_CURRENT_THEME),
			'portfolio_4_name' => __('Portfolio 4 columns items amount', HS_CURRENT_THEME),
			'portfolio_4_desc' => __('Portfolio items amount for Portfolio 4 columns template.', HS_CURRENT_THEME),
			
			//Footer options
			'footer' => __('Footer', HS_CURRENT_THEME),
			'copyright_text_name' => __('Footer copyright text', HS_CURRENT_THEME),
			'copyright_text_desc' => __('Enter text used in the right side of the footer. HTML tags are allowed.', HS_CURRENT_THEME),
			'google_name' => __('Google Analytics Code', HS_CURRENT_THEME),
			'google_desc' => __('You can paste your Google Analytics or other tracking code in this box. This will be automatically added to the footer.', HS_CURRENT_THEME),
			'feedburner_name' => __('Feedburner URL', HS_CURRENT_THEME),
			'feedburner_desc' => __('Feedburner is a Google service that takes care of your RSS feed. Paste your Feedburner URL here to let readers see it in your website.', HS_CURRENT_THEME),
			'footer_menu_name' => __('Display Footer Menu?', HS_CURRENT_THEME),
			'footer_menu_desc' => __('Do you want to display footer menu?', HS_CURRENT_THEME),
			'footer_menu_typography_name' => __('Footer Menu Typography', HS_CURRENT_THEME),
			'footer_menu_typography_desc' => __('Choose your prefered font for menu. <em>Note: fonts marked with <strong>*</strong> symbol will be loaded from the <a href="http://www.google.com/webfonts">Google Web Fonts</a> library.</em>', HS_CURRENT_THEME),
			
			//Other theme options
			'no_repeat' => __('No Repeat', HS_CURRENT_THEME),
			'r_h' => __('Repeat Horizontally', HS_CURRENT_THEME),
			'r_v' => __('Repeat Vertically', HS_CURRENT_THEME),
			'r_a' => __('Repeat All', HS_CURRENT_THEME),
			't_l' => __('Top Left', HS_CURRENT_THEME),
			't_c' => __('Top Center', HS_CURRENT_THEME),
			't_r' => __('Top Right', HS_CURRENT_THEME),
			'm_l' => __('Middle Left', HS_CURRENT_THEME),
			'm_c' => __('Middle Center', HS_CURRENT_THEME),
			'm_r' => __('Middle Right', HS_CURRENT_THEME),
			'b_l' => __('Bottom Left', HS_CURRENT_THEME),
			'b_c' => __('Bottom Center', HS_CURRENT_THEME),
			'b_r' => __('Bottom Right', HS_CURRENT_THEME),
			's_n' => __('Scroll Normally', HS_CURRENT_THEME),
			'f_p' => __('Fixed in Place', HS_CURRENT_THEME),
			
			//import & export options
			'Step_1' => __('<span>Step <i>1</i></span>Theme Options Import', HS_CURRENT_THEME),
			'Select the file that contains Theme Options' => __('Select the file that contains Theme Options (e.g. <b>options.json</b> )', HS_CURRENT_THEME),
			'Upload File and Import' => __('Upload File and Import', HS_CURRENT_THEME),
			'Step_1_export' => __('<span>Step <i>1</i></span>Theme Options Export', HS_CURRENT_THEME),
			'Welcome to the OptionsFramework Backup Manager' => __('Welcome to the OptionsFramework Backup Manager.', HS_CURRENT_THEME),
			'problem_importing' => __('There was a problem importing your settings. Please Try again.', HS_CURRENT_THEME),
			'problem_exporting' => __('There was a problem exporting your settings. Please Try again.', HS_CURRENT_THEME),
			'provided_is_invalid.' => __('The import file you\'ve provided is invalid. Please try again.', HS_CURRENT_THEME),
			
			'step_1_export_widget' => __('<span>Step <i>1</i></span> Widget Settings Export', HS_CURRENT_THEME),
			'step_3' => __('<span>Step <i>3</i></span> Widget Settings Import', HS_CURRENT_THEME),
			'step_4' => __('<span>Step <i>4</i></span> Widget Settings Import', HS_CURRENT_THEME),
			'import_settings' => __('Import Settings', HS_CURRENT_THEME),
			'please_try_again' => __("Incorrect file. Please, <a href='admin.php?page=options-framework-import&amp;step=1'>try again</a>.", HS_CURRENT_THEME),
			'select_the_file' => __('Select the file that contains Widget Settings (e.g. <b>your_template_package/sources/sample_data/widgets.json</b>)', HS_CURRENT_THEME),
			'show_widget_settings' => __('Show Widget Settings', HS_CURRENT_THEME),
			'no_widget' => __('Your have no widgets. Please, click next to go to the next step.', HS_CURRENT_THEME),
			'widget_import_warning' => __('Disable the widgets you don\'t need and click "Next". All the selected widgets will be imported into the theme by default.', HS_CURRENT_THEME),
			'go_to_widgets' => __('go to widgets', HS_CURRENT_THEME),
			
			//wordpress-importer.php
			'sorry' => __('Sorry, there has been an error.', HS_CURRENT_THEME),
			'not_exist' => __('The file does not exist, please ', HS_CURRENT_THEME),
			'please' => __('Please', HS_CURRENT_THEME),
			'WXR_file' => __('This WXR file (version %s) may not be supported by this version of the importer. Please consider updating.', HS_CURRENT_THEME),
			'export_file' => __('The export file could not be found at <code>%s</code>. It is likely that this was caused by a permissions problem.', HS_CURRENT_THEME),
			'import_author' => __('Failed to import author %s. Their posts will be attributed to the current user.', HS_CURRENT_THEME),
			'Assign Authors' => __('Assign Authors', HS_CURRENT_THEME),
			'To make it easier' => __('To make it easier for you to edit and save the imported content, you may want to reassign the author of the imported item to an existing user of this site. For example, you may want to import all the entries as <b>admin</b> entries.', HS_CURRENT_THEME),
			'If a new user is' => __('If a new user is created by WordPress, a new password will be randomly generated and the new user&#8217;s role will be set as %s. Manually changing the new user&#8217;s details will be necessary.', HS_CURRENT_THEME),
			'Download and import' => __('Download and import file attachments', HS_CURRENT_THEME),
			'import_data' => __('Import Data', HS_CURRENT_THEME),
			'import_author_2' => __('Import author:', HS_CURRENT_THEME),
			'existing_user' => __('assign posts to an existing user:', HS_CURRENT_THEME),
			'select' => __('- Select -', HS_CURRENT_THEME),
			'create_new_user' => __('Failed to create new user for %s. Their posts will be attributed to the current user.', HS_CURRENT_THEME),
			'import_category ' => __('Failed to import category %s ', HS_CURRENT_THEME),
			'import_post_tag' => __('Failed to import post tag %s', HS_CURRENT_THEME),
			'failed_to_import' => __('Failed to import %s %s ', HS_CURRENT_THEME),
			'failed_to_import_2' => __('Failed to import &#8220;%s&#8221;: Invalid post type %s ', HS_CURRENT_THEME),
			'already_exists' => __('%s &#8220;%s&#8221; already exists.', HS_CURRENT_THEME),
			'failed_to_import_3' => __('Failed to import %s &#8220;%s&#8221; ', HS_CURRENT_THEME),
			'menu_item' => __('Menu item skipped due to missing menu slug ', HS_CURRENT_THEME),
			'menu_item_2' => __('Menu item skipped due to invalid menu slug: %s ', HS_CURRENT_THEME),
			'attachments' => __('Fetching attachments is not enabled ', HS_CURRENT_THEME),
			'Invalid file type' => __('Invalid file type', HS_CURRENT_THEME),
			'remote' => __('Remote server did not respond', HS_CURRENT_THEME),
			'remote_2' => __('Remote server returned error response %1$d %2$s ', HS_CURRENT_THEME),
			'remote_3' => __('Remote file is incorrect size ', HS_CURRENT_THEME),
			'zero_size' => __('Zero size file downloaded ', HS_CURRENT_THEME),
			'remote_4' => __('Remote file is too large, limit is %s ', HS_CURRENT_THEME),
			'step_1' => __('<span>Step <i>1</i></span> Data Import', HS_CURRENT_THEME),
			'step_2' => __('<span>Step <i>2</i></span> Assign Authors', HS_CURRENT_THEME),
			'A new version of' => __('A new version of this importer is available. Please update to version %s to ensure compatibility with newer export files. ', HS_CURRENT_THEME),
			'select_xml' => __('Select (<b>.xml</b>) file to upload sample data.<br>If you do not want to install sample data from livedemo you need to <b>skip this step</b>.', HS_CURRENT_THEME),
			'sample_data_import_warning' => __('Please note that certain content is already installed. You may simply need to skip this step. Otherwise, you can proceed with the installation.', HS_CURRENT_THEME),
			
			'server_settings_error' => __('Some of your server settings do not meet the requirements for installing the sample data. Please, consult with your hosting provider on how to increase the required values.', HS_CURRENT_THEME),
			'server_settings' => __('Server Settings', HS_CURRENT_THEME),
			'current' => __('Current', HS_CURRENT_THEME),
			'note' => __('NOTE', HS_CURRENT_THEME),
			'settings_can_not_be_adjusted' => __('if for some reason those settings can not be adjusted, you may install the sample data using an <strong>alternative method</strong> - importing the <strong>.sql</strong> file directly into the database. Refer to the template documentation for instructions.', HS_CURRENT_THEME),
			'template_installation' => __('You can proceed with the template installation without updating server settings, however in this case you can get errors or only part of your content will be loaded.', HS_CURRENT_THEME),
			'congratulations' => __('Congratulations', HS_CURRENT_THEME),
			'congratulations_msg' => __('You have successfully installed your <b>WordPress Theme</b>.<br /> You can look theme now', HS_CURRENT_THEME),
			'visit_site' => __('visit site', HS_CURRENT_THEME),
			'settings_output_buffering' => __('You might see only the white screen on the next step. Don\'t worry, the importing is being continued. Please wait until the installation is finished.', HS_CURRENT_THEME),
			'jigoshop_attention' => __('<b>Attention:</b> the Jigoshop plugin is not activated. We recommend that you install and activate this plugin to ensure correct data importing. Otherwise, some data may be lost during the import.', HS_CURRENT_THEME),
			'woocommerce_attention' => __('<b>Attention:</b> the WooCommerce plugin is not activated. We recommend that you install and activate this plugin to ensure correct data importing. Otherwise, some data may be lost during the import.', HS_CURRENT_THEME),

			//function.php
			'login_error' => __('The login information you have entered is incorrect.', HS_CURRENT_THEME),
			'warning_notice_1' => __('You need to enable write permissions on your server to use these functions.', HS_CURRENT_THEME),
			'warning_notice_2' => __('Theme Framework is not able to perform necessary changes for the correct work with your child theme.', HS_CURRENT_THEME),
			'warning_notice_3' => __('See <a target="_blank" href="http://codex.wordpress.org/Changing_File_Permissions">the Codex</a> for more information.', HS_CURRENT_THEME),
			
			//theme-init.php
			'header_menu' => __('Header Menu', HS_CURRENT_THEME),
			'footer_menu' => __('Footer Menu', HS_CURRENT_THEME),
			'slides' => __('Slides', HS_CURRENT_THEME),
			'testimonial' => __('Testimonial', HS_CURRENT_THEME),
			'services' => __('Services', HS_CURRENT_THEME),
			'faqs' => __('FAQs', HS_CURRENT_THEME),
			'our_team' => __('Our Team', HS_CURRENT_THEME),
			'category' => __('Category', HS_CURRENT_THEME),
			'tag' => __('Tag', HS_CURRENT_THEME),
			
			//theme-function.php
			'thumbnail' => __('Thumbnail', HS_CURRENT_THEME),
			'your_comment' => __('Your comment is awaiting moderation.', HS_CURRENT_THEME),

			//theme-portfoliometa.php
			'portfolio_format' => __('Please choose desired Portfolio Format and fill additional fields.', HS_CURRENT_THEME),
			'slideshow' => __('Slideshow', HS_CURRENT_THEME),
			'grid_gallery' => __('Grid Gallery', HS_CURRENT_THEME),
			'portfolio_options' => __('Portfolio Options', HS_CURRENT_THEME),
			'format' => __('Format', HS_CURRENT_THEME),
			'format_desc' => __('Choose post format that most fit your needs.', HS_CURRENT_THEME),
			'date_desc' => __('Input project end date.', HS_CURRENT_THEME),
			'client' => __('Client', HS_CURRENT_THEME),
			'client_desc' => __('Input project owner name.', HS_CURRENT_THEME),
			'info_desc' => __('Additional info for this portfolio item.', HS_CURRENT_THEME),
			'url_desc' => __('Input the project URL (external link)', HS_CURRENT_THEME),
			'image_settings' => __('Image Settings', HS_CURRENT_THEME),
			'video_settings' => __('Video Settings', HS_CURRENT_THEME),
			'video_settings_desc' => __('Input the video title (for playlist)', HS_CURRENT_THEME),
			'artist' => __('Artist', HS_CURRENT_THEME),
			'artist_desc' => __('Input the video artist (for playlist).', HS_CURRENT_THEME),
			'url_1_desc' => __('Input URL to the <b>m4v</b> video format.', HS_CURRENT_THEME),
			'url_2_desc' => __('Input URL to the <b>ogv</b> video format.', HS_CURRENT_THEME),
			'embedded_code' => __('Embedded Code', HS_CURRENT_THEME),
			'embedded_code_desc' => __('You can include embedded code here.<br><b>Attention!</b> This code overwrite your video URL(s).', HS_CURRENT_THEME),
			'audio_settings' => __('Audio Settings', HS_CURRENT_THEME),
			'audio_title_desc' => __('Input the audio title (for playlist).', HS_CURRENT_THEME),
			'audio_artist_desc' => __('Input the audio artist (for playlist).', HS_CURRENT_THEME),
			'audio_format' => __('Audio format', HS_CURRENT_THEME),
			'audio_format_desc' => __('Choose audio format.', HS_CURRENT_THEME),
			'audio_url' => __('Audio URL', HS_CURRENT_THEME),
			'audio_url_desc' => __('Input the audio URL.', HS_CURRENT_THEME),
			
			//theme-slidermeta.php
			'slider_options' => __('Slider Options', HS_CURRENT_THEME),
			'caption' => __('Caption', HS_CURRENT_THEME),
			'caption_desc' => __('Input your caption for slide (HTML tags are allowed).', HS_CURRENT_THEME),
			'url_desc_slidermeta' => __('Input the slide URL (can be external link)', HS_CURRENT_THEME),
			'slider_options_desc' => __('Please fill additional fields for slide.', HS_CURRENT_THEME),
			
			//theme-teammeta.php
			'personal_options' => __('Personal Options', HS_CURRENT_THEME),
			'personal_options_desc' => __('Please fill additional fields for person.', HS_CURRENT_THEME),
			'position' => __('Position', HS_CURRENT_THEME),
			'position_desc' => __('Input position of the person.', HS_CURRENT_THEME),
			'info_desc_2' => __('Input additional info.', HS_CURRENT_THEME),
			's_n' => __('Social Networks', HS_CURRENT_THEME),
			'page_url' => __('Page URL', HS_CURRENT_THEME),
			'your_s_n' => __('Your Social Networks.', HS_CURRENT_THEME),
			'icon_desc' => __('In icon field you need to specify the icon name that can be copied from the <a target="_blank" href="http://fortawesome.github.io/Font-Awesome/icons/#brand">website</a>. E.g. "icon-facebook".', HS_CURRENT_THEME),
			'network_title' => __('Social Networks Title', HS_CURRENT_THEME),
			'network_title_desc' => __('Specify the heading for the social networks block.', HS_CURRENT_THEME),

			//theme-testimeta.php
			'testimonial_options' => __('Testimonial Options', HS_CURRENT_THEME),
			'testimonial_options_desc' => __('Please fill additional fields for testimonial.', HS_CURRENT_THEME),
			'name' => __('Name', HS_CURRENT_THEME),
			'name_desc' => __('Input author\'s name.', HS_CURRENT_THEME),
			'url_desc_2' => __('Input author\'s URL.', HS_CURRENT_THEME),
			'info_desc_3' => __('Input author\'s additional info.', HS_CURRENT_THEME),
			
			//theme-postmeta.php
			'quote_settings' => __('Quote Settings', HS_CURRENT_THEME),
			'quote' => __('The Quote', HS_CURRENT_THEME),
			'quote_desc' => __('Put your quote in this field.', HS_CURRENT_THEME),
			'author' => __('Author', HS_CURRENT_THEME),
			'author_desc' => __('Put quote author in this field.', HS_CURRENT_THEME),
			'link_settings' => __('Link Settings', HS_CURRENT_THEME),
			'the_url' => __('The URL', HS_CURRENT_THEME),
			'the_url_desc' => __('Insert the URL you wish to link to.', HS_CURRENT_THEME),
			'image_settings' => __('Image Settings', HS_CURRENT_THEME),
			'title_desc' => __('Input the video title (for playlist).', HS_CURRENT_THEME),

			//theme-pagemeta.php
			'category_include' => __('Category Include', HS_CURRENT_THEME),
			'category_slug' => __('The Category Slug', HS_CURRENT_THEME),
			'category_desc' => __('Name of the custom category that is displayed on this page. You need to use the slug of the category here.', HS_CURRENT_THEME),
			
			//class-tgm-plugin-activation.php, register-plugins.php
			'page_title' => __('Install Required Plugins', HS_CURRENT_THEME),
			'menu_title' => __('Install Plugins', HS_CURRENT_THEME),
			'installing' => __('Installing Plugin: %s', HS_CURRENT_THEME),
			'oops' => __('Something went wrong', HS_CURRENT_THEME),
			'notice_can_install_required' => __('This theme requires the following plugin: %1$s.', HS_CURRENT_THEME),
			'notice_can_install_required_2' => __('This theme requires the following plugins: %1$s.', HS_CURRENT_THEME),
			'notice_can_install_recommended' => __('This theme recommends the following plugin: %1$s.', HS_CURRENT_THEME),
			'notice_can_install_recommended_2' => __('This theme recommends the following plugins: %1$s.', HS_CURRENT_THEME),
			'notice_cannot_install' => __('Sorry, but you do not have the correct permissions to install the %s plugin. Contact the administrator of this site for help on getting the plugin installed.', HS_CURRENT_THEME),
			'notice_cannot_install_2' => __('Sorry, but you do not have the correct permissions to install the %s plugins. Contact the administrator of this site for help on getting the plugins installed.', HS_CURRENT_THEME),
			'notice_can_activate_required' => __('The following required plugin is currently inactive: %1$s.', HS_CURRENT_THEME),
			'notice_can_activate_required_2' => __('The following required plugins are currently inactive: %1$s.', HS_CURRENT_THEME),
			'notice_can_activate_recommended' => __('The following recommended plugin is currently inactive: %1$s', HS_CURRENT_THEME),
			'notice_can_activate_recommended_2' => __('The following recommended plugins are currently inactive: %1$s.', HS_CURRENT_THEME),
			'notice_cannot_activate' => __('Sorry, but you do not have the correct permissions to activate the %s plugin. Contact the administrator of this site for help on getting the plugin activated.', HS_CURRENT_THEME),
			'notice_cannot_activate_2' => __('Sorry, but you do not have the correct permissions to activate the %s plugins. Contact the administrator of this site for help on getting the plugins activated.', HS_CURRENT_THEME),
			'notice_ask_to_update' => __('The following plugin needs to be updated to its latest version to ensure maximum compatibility with this theme: %1$s.', HS_CURRENT_THEME),
			'notice_ask_to_update_2' => __('The following plugins need to be updated to their latest version to ensure maximum compatibility with this theme: %1$s', HS_CURRENT_THEME),
			'notice_cannot_update' => __('Sorry, but you do not have the correct permissions to update the %s plugin. Contact the administrator of this site for help on getting the plugin updated.', HS_CURRENT_THEME),
			'notice_cannot_update_2' => __('Sorry, but you do not have the correct permissions to update the %s plugins. Contact the administrator of this site for help on getting the plugins updated.', HS_CURRENT_THEME),
			'install_link' => __('Begin installing plugin', HS_CURRENT_THEME),
			'install_link_2' => __('Begin installing plugins', HS_CURRENT_THEME),
			'activate_link' => __('Activate installed plugin', HS_CURRENT_THEME),
			'activate_link_2' => __('Activate installed plugins', HS_CURRENT_THEME),
			'return' => __('Return to Required Plugins Installer', HS_CURRENT_THEME),
			'plugin_activated' => __('Plugin activated successfully', HS_CURRENT_THEME),
			'complete' => __('All plugins installed and activated successfully. %1$s', HS_CURRENT_THEME),
			'dashboard' => __('Return to the Dashboard', HS_CURRENT_THEME),
			'following_plugin' => __('The following plugin was activated successfully: %s.', HS_CURRENT_THEME),
			'dismiss' => __('Dismiss this notice', HS_CURRENT_THEME),
			'external_link' => __('External Link', HS_CURRENT_THEME),
			'private_repository' => __('Private Repository', HS_CURRENT_THEME),
			'pre_packaged' => __('Pre-Packaged', HS_CURRENT_THEME),
			'wordpress_repository' => __('WordPress Repository', HS_CURRENT_THEME),
			'required' => __('Required', HS_CURRENT_THEME),
			'recommended' => __('Recommended', HS_CURRENT_THEME),
			'not_installed' => __('Not Installed', HS_CURRENT_THEME),
			'installed_but' => __('Installed But Not Activated', HS_CURRENT_THEME),
			'no_plugins' => __("No plugins to install or activate.", HS_CURRENT_THEME),
			'r_dashboard' => __("Return to the Dashboard", HS_CURRENT_THEME),
			'plugin_' => __('Plugin', HS_CURRENT_THEME),
			'source' => __('Source', HS_CURRENT_THEME),
			'type' => __('Type', HS_CURRENT_THEME),
			'status' => __('Status', HS_CURRENT_THEME),
			'install' => __('Install', HS_CURRENT_THEME),
			'activate' => __('Activate', HS_CURRENT_THEME),
			'following_plugin' => __('The following plugin was activated successfully:', HS_CURRENT_THEME),
			'following_plugins' => __('The following plugins were activated successfully:', HS_CURRENT_THEME),
			'no_package' => __('Install package not available.', HS_CURRENT_THEME),
			'downloading_package' => __("Downloading install package from <span class='code'>%s</span>&#8230;", HS_CURRENT_THEME),
			'unpack_package' => __('Unpacking the package&#8230;', HS_CURRENT_THEME),
			'installing_package' => __('Installing the plugin&#8230;', HS_CURRENT_THEME),
			'process_failed' => __('Plugin install failed.', HS_CURRENT_THEME),
			'process_success' => __('Plugin installed successfully.', HS_CURRENT_THEME),
			'activation_failed' => __('Plugin activation failed.', HS_CURRENT_THEME),
			'activation_success' => __('Plugin activated successfully.', HS_CURRENT_THEME),
			'skin_upgrade_start' => __('The installation and activation process is starting. This process may take a while on some hosts, so please be patient.', HS_CURRENT_THEME),
			'skin_update_successful' => __('%1$s installed and activated successfully.', HS_CURRENT_THEME),
			'skin_update_successful_2' => __('Show Details', HS_CURRENT_THEME),
			'skin_update_successful_3' => __('Hide Details', HS_CURRENT_THEME),
			'skin_upgrade_end' => __('All installations and activations have been completed.', HS_CURRENT_THEME),
			'skin_before_update_header' => __('Installing and Activating Plugin %1$s (%2$d/%3$d)', HS_CURRENT_THEME),
			'skin_upgrade_start_2' => __('The installation process is starting. This process may take a while on some hosts, so please be patient.', HS_CURRENT_THEME),
			'skin_update_failed_error' => __('An error occurred while installing %1$s: <strong>%2$s</strong>.', HS_CURRENT_THEME),
			'skin_update_failed' => __('The installation of %1$s failed.', HS_CURRENT_THEME),
			'skin_update_successful_4' => __('%1$s installed successfully.', HS_CURRENT_THEME),
			'skin_upgrade_end_2' => __('All installations have been completed.', HS_CURRENT_THEME),
			'skin_before_update_header_2' => __('Installing Plugin %1$s (%2$d/%3$d)', HS_CURRENT_THEME),
			'oops_2' => __('Something went wrong with the plugin API._', HS_CURRENT_THEME),
			'updated' => __('updated', HS_CURRENT_THEME),

			//class.wp-help-pointers.php
			'pointer_close' => __('Close', HS_CURRENT_THEME),

			//sidebar-init.php
			'sidebar' => __('Sidebar', HS_CURRENT_THEME),
			'sidebar_desc' => __('Located at the right side of pages.', HS_CURRENT_THEME),
			'footer_1' => __('Footer Area 1', HS_CURRENT_THEME),
			'footer_2' => __('Footer Area 2', HS_CURRENT_THEME),
			'footer_3' => __('Footer Area 3', HS_CURRENT_THEME),
			'footer_4' => __('Footer Area 4', HS_CURRENT_THEME),
			'footer_desc' => __('Located at the bottom of pages.', HS_CURRENT_THEME),
			'archives' => __('Archives', HS_CURRENT_THEME),
			'meta' => __('Meta', HS_CURRENT_THEME),
			
			//post-meta.php
			'no_comments' => __('0', HS_CURRENT_THEME),
			'comment' => __('1', HS_CURRENT_THEME),
			'comments' => __('', HS_CURRENT_THEME),
			'comments_link' => __('comments-link', HS_CURRENT_THEME),
			'comments_closed' => __('0', HS_CURRENT_THEME),
			'has_not_tags' => __('No tags', HS_CURRENT_THEME),
			'number_views' => __('Number of view.', HS_CURRENT_THEME),
			'like' => __('I like it.', HS_CURRENT_THEME),
			'dislike' => __('I don\'t like.', HS_CURRENT_THEME),
			'not_voting' => __('Only registered users can vote!', HS_CURRENT_THEME),
			'have_voting' => __('You have already voted.', HS_CURRENT_THEME),
			
			//post-nav.php
			'older' => __('&laquo; Older Entries', HS_CURRENT_THEME),
			'newer' => __('Newer Entries &raquo;', HS_CURRENT_THEME),

			//dialog.php
			'shortcode_options' => __('Shortcode Options', HS_CURRENT_THEME),
			'cancel' => __('Cancel', HS_CURRENT_THEME),
			'insert_shortcode' => __('Insert Shortcode', HS_CURRENT_THEME),
			
			//editor_plugin.php
			'posts' => __('Posts', HS_CURRENT_THEME),
			'posts_grid' => __('Posts Grid', HS_CURRENT_THEME),
			'posts_list' => __('Posts List', HS_CURRENT_THEME),
			'mini_posts_grid' => __('Mini Posts Grid', HS_CURRENT_THEME),
			'mini_posts_list' => __('Mini Posts List', HS_CURRENT_THEME),
			'recentposts' => __('Recent Posts', HS_CURRENT_THEME),
			'recenttesti' => __('Recent Testimonials', HS_CURRENT_THEME),
			'basic' => __('Basic', HS_CURRENT_THEME),
			'banner' => __('Banner', HS_CURRENT_THEME),
			'recentcomments' => __('Comments', HS_CURRENT_THEME),
			'post_cycle' => __('Post Cycle', HS_CURRENT_THEME),
			'carousel' => __('Carousel', HS_CURRENT_THEME),
			'roundabout' => __('Roundabout', HS_CURRENT_THEME),
			'service_box' => __('Service Box', HS_CURRENT_THEME),
			'hero_unit' => __('Hero Unit', HS_CURRENT_THEME),
			'columns' => __('Columns', HS_CURRENT_THEME),
			'fluid_column' => __('Fluid Column', HS_CURRENT_THEME),
			'2_columns' => __('2 Columns', HS_CURRENT_THEME),
			'3_columns' => __('3 Columns', HS_CURRENT_THEME),
			'4_columns' => __('4 Columns', HS_CURRENT_THEME),
			'elements' => __('Elements', HS_CURRENT_THEME),
			'label' => __('Label', HS_CURRENT_THEME),
			'highlight' => __('Text Highlight', HS_CURRENT_THEME),
			'button' => __('Button', HS_CURRENT_THEME),
			'dropcap' => __('Drop Cap', HS_CURRENT_THEME),
			'blockquote' => __('Blockquote', HS_CURRENT_THEME),
			'icon' => __('Icon', HS_CURRENT_THEME),
			'frame' => __('Frame', HS_CURRENT_THEME),
			'hr' => __('Horizontal Rule', HS_CURRENT_THEME),
			'sm_hr' => __('Small Horizontal Rule', HS_CURRENT_THEME),
			'vr' => __('Vertical Rule', HS_CURRENT_THEME),
			'spacer' => __('Spacer', HS_CURRENT_THEME),
			'progressbar' => __('Progressbar', HS_CURRENT_THEME),
			'address' => __('Address', HS_CURRENT_THEME),
			'clear' => __('Clear', HS_CURRENT_THEME),
			'extra_wrap' => __('Extra Wrap', HS_CURRENT_THEME),
			'lists' => __('Lists', HS_CURRENT_THEME),
			'list_un' => __('Unstyled', HS_CURRENT_THEME),
			'check_list' => __('Check List', HS_CURRENT_THEME),
			'check2_list' => __('Check 2 List', HS_CURRENT_THEME),
			'arrow_list' => __('Arrow List', HS_CURRENT_THEME),
			'arrow2_list' => __('Arrow 2 List', HS_CURRENT_THEME),
			'star_list' => __('Star List', HS_CURRENT_THEME),
			'plus_list' => __('Plus List', HS_CURRENT_THEME),
			'minus_list' => __('Minus List', HS_CURRENT_THEME),
			'custom_list' => __('Custom List', HS_CURRENT_THEME),
			'audio_video' => __('Audio & Video', HS_CURRENT_THEME),
			'video_preview' => __('Video Preview', HS_CURRENT_THEME),
			'misc' => __('Misc', HS_CURRENT_THEME),
			'alert_box' => __('Alert Box', HS_CURRENT_THEME),
			'close' => __('Close icon', HS_CURRENT_THEME),
			'well' => __('Well', HS_CURRENT_THEME),
			'small' => __('Small', HS_CURRENT_THEME),
			'title_box' => __('Title Box', HS_CURRENT_THEME),
			'template_url' => __('Template URL', HS_CURRENT_THEME),
			'tabs' => __('Tabs', HS_CURRENT_THEME),
			'accordions' => __('Accordion', HS_CURRENT_THEME),
			'table' => __('Table', HS_CURRENT_THEME),
			'map' => __('Google Map', HS_CURRENT_THEME),
			'site_map' => __('Sitemap', HS_CURRENT_THEME),
			
			//my-banners-widget.php
			'add_125_125' => __('Add 125x125 ads.', HS_CURRENT_THEME),
			'add_125_125_desc' => __('125x125 Ads', HS_CURRENT_THEME),
			'ad_1' => __('Ad 1', HS_CURRENT_THEME),
			'ad_2' => __('Ad 2', HS_CURRENT_THEME),
			'ad_3' => __('Ad 3', HS_CURRENT_THEME),
			'ad_4' => __('Ad 4', HS_CURRENT_THEME),
			'image_ad_link' => __('Image Ad Link:', HS_CURRENT_THEME),
			'ad_link' => __('Ad Link:', HS_CURRENT_THEME),
			
			//my-comment-widget.php
			'recent_comments' => __('Recent Comments', HS_CURRENT_THEME),
			'recent_comments_decs' => __('My Recent Comments', HS_CURRENT_THEME),
			'go_to_c' => __('Go to this comment', HS_CURRENT_THEME),
			'comments_count' => __('Number of comments to show', HS_CURRENT_THEME),
			'display_avatar' => __('Display avatar', HS_CURRENT_THEME),
			'avatar_size' => __('Avatar size (px)', HS_CURRENT_THEME),
			'display_author_name' => __('Display the comment author', HS_CURRENT_THEME),
			'display_date' => __('Display the comment date', HS_CURRENT_THEME),
			'display_post_title' => __('Display post title', HS_CURRENT_THEME),
			'meta_format' => __('Meta format', HS_CURRENT_THEME),
			'comment_date' => __('Date', HS_CURRENT_THEME),
			'comment_author' => __('Author', HS_CURRENT_THEME),
			'comment_in' => __('Comment in', HS_CURRENT_THEME),
			
			//my-flickr-widget.php
			'flickr' => __('Flickr', HS_CURRENT_THEME),
			'flickr_id' => __('Flickr ID:', HS_CURRENT_THEME),
			'images_count' => __('Images count:', HS_CURRENT_THEME),
			
			//my-posts-type-widget.php
			'advanced_cycle' => __('Advanced Cycle', HS_CURRENT_THEME),
			'advanced_cycle_desc' => __('Show custom posts', HS_CURRENT_THEME),
			'posts_type' => __('Posts type', HS_CURRENT_THEME),
			'posts_num' => __('Number of posts to show', HS_CURRENT_THEME),
			'sort_by' => __('Sort by', HS_CURRENT_THEME),
			'reverse_sort' => __('Reverse sort order (ascending)', HS_CURRENT_THEME),
			'show_number' => __('Show number of comments', HS_CURRENT_THEME),
			'show_meta' => __('Show meta', HS_CURRENT_THEME),
			'container_class' => __('Container class', HS_CURRENT_THEME),
			'default_featured_custom' => __('(default: "featured_custom_posts")', HS_CURRENT_THEME),
			'post_title' => __('Post title', HS_CURRENT_THEME),
			'show_post_title' => __('Show post title', HS_CURRENT_THEME),
			'date_as_title' => __("Date as title <span style='font-size:11px; color:#999;'>('[mm-dd-yyyy]')</span>", HS_CURRENT_THEME),
			'excerpt' => __('Excerpt', HS_CURRENT_THEME),
			'post_excerpt' => __('Show post excerpt', HS_CURRENT_THEME),
			'excerpt_link' => __('Excerpt as link', HS_CURRENT_THEME),
			'more_link' => __('More link', HS_CURRENT_THEME),
			'show_more_link' => __('Show "More link', HS_CURRENT_THEME),
			'default_read_more' => __('(default: "Read more")', HS_CURRENT_THEME),
			'link_class' => __('Link class', HS_CURRENT_THEME),
			'default_link' => __('(default: "link")', HS_CURRENT_THEME),
			'thumbnail_dimensions' => __('Thumbnail dimensions', HS_CURRENT_THEME),
			'show_post_thumbnail' => __('Show post thumbnail', HS_CURRENT_THEME),
			'thumbnail_as_link' => __('Thumbnail as link', HS_CURRENT_THEME),
			'all_posts_link' => __('Link to all posts', HS_CURRENT_THEME),
			'show_global_link' => __('Show global link to all posts', HS_CURRENT_THEME),
			'default_view_all' => __('(default: "View all")', HS_CURRENT_THEME),
			
			//my-recent-posts
			'recent_posts' => __('Recent Posts', HS_CURRENT_THEME),
			'permanent_link_to' => __('Permanent Link to', HS_CURRENT_THEME),
			'category_slug' => __('Category Slug:', HS_CURRENT_THEME),
			'post_format' => __('Post format:', HS_CURRENT_THEME),
			'post_order' => __('Post order:', HS_CURRENT_THEME),
			'posts_per_page' => __('Posts per page:', HS_CURRENT_THEME),
			
			//my-social-widget.php
			'social_networks' => __('Social Networks', HS_CURRENT_THEME),
			'social_networks_desc' => __('Link to your social networks.', HS_CURRENT_THEME),
			//'label' => __(' label:', HS_CURRENT_THEME),
			'display' => __('Display:', HS_CURRENT_THEME),
			'icons' => __('Icons', HS_CURRENT_THEME),
			'labels' => __('Labels', HS_CURRENT_THEME),
			'both' => __('Both', HS_CURRENT_THEME),
			
			//my-twitter-widget.php
			'twitter' => __('Twitter', HS_CURRENT_THEME),
			'twitter_name' => __('Twitter Name:', HS_CURRENT_THEME),
			'twitter_num' => __('Twitts Number:', HS_CURRENT_THEME),
			
			//my-vcard-widget.php
			'vCard_name' => __('vCard', HS_CURRENT_THEME),
			'vCard_desc' => __('Use this widget to add a vCard', HS_CURRENT_THEME),
			'vCard' => __('vCard', HS_CURRENT_THEME),
			'street' => __('Street Address:', HS_CURRENT_THEME),
			'map_url' => __('HTML map code:', HS_CURRENT_THEME),
			'map_width' => __('Map width:', HS_CURRENT_THEME),
			'map_height' => __('Map height:', HS_CURRENT_THEME),
			'gmap_disable' => __('Display map', HS_CURRENT_THEME),
			'city' => __('City/Locality:', HS_CURRENT_THEME),
			'state' => __('State/Region:', HS_CURRENT_THEME),
			'zipcode' => __('Zipcode/Postal Code:', HS_CURRENT_THEME),
			'telephone' => __('Telephone:', HS_CURRENT_THEME),
			'email' => __('Email:', HS_CURRENT_THEME),

			//my-facebook-widget.php
			'facebook_widget_name' => __('Facebook Like Box Widget', HS_CURRENT_THEME),
			'facebook_widget_disc' => __('Facebook Like Box Widget', HS_CURRENT_THEME),
			'facebook_url' => __('Facebook page url', HS_CURRENT_THEME),
			'facebook_desc' => __('The Like Box only works with <a target="_blank" href="https://www.facebook.com/help/174987089221178/" title="Facebook Pages">Facebook Pages.</a>', HS_CURRENT_THEME),
			'color_scheme' => __('Color Scheme', HS_CURRENT_THEME),
			'light' => __('Light', HS_CURRENT_THEME),
			'dark' => __('Dark', HS_CURRENT_THEME),
			'display_haeder' => __('Display header', HS_CURRENT_THEME),
			'display_stream' => __('Display stream', HS_CURRENT_THEME),
			'display_border' => __('Display border', HS_CURRENT_THEME),
			'display_faces' => __('Display faces', HS_CURRENT_THEME),
			'facebook_title' => __('My Facebook Page', HS_CURRENT_THEME),
			'facebook_error' => __('Facebook error', HS_CURRENT_THEME),

			//options-framework.php
			'default_options' => __('Default options restored.', HS_CURRENT_THEME),
			'options_saved' => __('Options saved.', HS_CURRENT_THEME),
			'store' => __('Store', HS_CURRENT_THEME),
			'latest_templates' => __('Latest Templates', HS_CURRENT_THEME),
			'news_and_updates' => __('News & Updates', HS_CURRENT_THEME),
			'help_and_supports' => __('Help & Support', HS_CURRENT_THEME),
			'no_items' => __('No items', HS_CURRENT_THEME),
			'posted' => __('Posted', HS_CURRENT_THEME),
			'all_templates' => __('All templates', HS_CURRENT_THEME),

			//options-backup.php
			'start' => __('Start', HS_CURRENT_THEME),

			//data_management_interface.php
			'data_management' => __('Data Management', HS_CURRENT_THEME),
			'theme_framework' => __('Theme Framework', HS_CURRENT_THEME),
			'update_info' => __('Update Info', HS_CURRENT_THEME),
			'child_theme' => __('Child Theme', HS_CURRENT_THEME),
			'update' => __('Update', HS_CURRENT_THEME),
			'backup' => __('Backup', HS_CURRENT_THEME),
			'restore' => __('Restore', HS_CURRENT_THEME),
			'download_backup' => __('Download Backup', HS_CURRENT_THEME),
			'name' => __('Name', HS_CURRENT_THEME),
			'author' => __('Author', HS_CURRENT_THEME),
			'your_version' => __('Your Version', HS_CURRENT_THEME),
			'update_version' => __('Update Version', HS_CURRENT_THEME),
			'backup_version' => __('Backup Version', HS_CURRENT_THEME),
			'backup_date' => __('Last Backup Date', HS_CURRENT_THEME),
			'preview' => __('Preview', HS_CURRENT_THEME),
			'description' => __('Description', HS_CURRENT_THEME),
			'no_backup' => __('No backup.', HS_CURRENT_THEME),
			'not_defined' => __('Not defined', HS_CURRENT_THEME),
			'unfortunately' => __('Unfortunately theme ', HS_CURRENT_THEME),
			'please_try' => __(' backup file not found. Please try to create backup once again.', HS_CURRENT_THEME),
			'info_box_1' => __('Data Management allows to update or backup framework and themes. Framework is regularly updated thus delivering new opportunities for your site.<br> To keep your data safe, you can back up the framework or child theme, to be able to download it later. If necessary, you can restore the framework or your theme using the backup.', HS_CURRENT_THEME),
			'info_box_2' => __('<b>Warning!</b> Before updating framework you are strongly advised to backup your data.', HS_CURRENT_THEME),
			'info_box_3' => __('You can back up your theme. If the theme has a backup copy, it is possible to restore it or download. The date of the latest backup copy is displayed in the column <b>Last Backup Date</b>.', HS_CURRENT_THEME),
			'info_box_4' => __('<b style="color:red;">Warning!</b> Before updating framework you are strongly advised to <a href="admin.php?page=options-framework-data-management">backup</a> your data.', HS_CURRENT_THEME),

			
			//options-medialibrary-uploader.php
			'view_file' => __('View File', HS_CURRENT_THEME),
			'previously_uploaded' => __('Previously Uploaded', HS_CURRENT_THEME),
			
			//options-sanitize.php
			'latin' => __('Latin', HS_CURRENT_THEME),
			'latin_extended' => __('Latin Extended', HS_CURRENT_THEME),
			'greek' => __('Greek', HS_CURRENT_THEME),
			'greek_extended' => __('Greek Extended', HS_CURRENT_THEME),
			'cyrillic' => __('Cyrillic', HS_CURRENT_THEME),
			'cyrillic_extended' => __('Cyrillic Extended', HS_CURRENT_THEME),
			'vietnamese' => __('Vietnamese', HS_CURRENT_THEME),
			'normal' => __('Normal', HS_CURRENT_THEME),
			'italic' => __('Italic', HS_CURRENT_THEME),
			'bold' => __('Bold', HS_CURRENT_THEME),
			'bold_italic' => __('Bold Italic', HS_CURRENT_THEME),
			
			//parsers.php
			'there_was' => __('There was an error when reading this WXR file', HS_CURRENT_THEME),
			'details_are' => __('Details are shown above. The importer will now try again with a different parser...', HS_CURRENT_THEME),
			'SimpleXML_parse_error' => __('There was an error when reading this WXR file', HS_CURRENT_THEME),
			'WXR_parse_error' => __('This does not appear to be a WXR file, missing/invalid WXR version number', HS_CURRENT_THEME),
			
			//update.php
			'themes_api_failed' => __("<p>An Unexpected HTTP Error occurred during the API request.</p><p><a href='#' onclick='document.location.reload(); return false;'>Try again</a></p>", HS_CURRENT_THEME),
			'themes_api_failed_2' => __('An unknown error occurred', HS_CURRENT_THEME),
			'new_version' => __('There is a new version of theme framework available', HS_CURRENT_THEME),
			'view_version' => __('View version ', HS_CURRENT_THEME),
			'details' => __(' details', HS_CURRENT_THEME),
			'or' => __('or', HS_CURRENT_THEME),
			'update_now' => __('update now.', HS_CURRENT_THEME),
			'dismiss_notice' => __('Dismiss this notice', HS_CURRENT_THEME),
			
			//comments.php
			'please_do_not' => __('Please do not load this page directly. Thanks!', HS_CURRENT_THEME),
			'password' => __('This post is password protected. Enter the password to view comments.', HS_CURRENT_THEME),
			'response' => __('1 Response', HS_CURRENT_THEME),
			'responses' => __('%1$s Responses', HS_CURRENT_THEME),
			'no_comments_yet' => __('No Comments Yet.', HS_CURRENT_THEME),
			'comments_are_closed' => __('Comments are closed.', HS_CURRENT_THEME),
			'leave_a_reply' => __('Leave a comment', HS_CURRENT_THEME),
			'you_must_be' => __('You must be', HS_CURRENT_THEME),
			'post_a_comment' => __('to post a comment.', HS_CURRENT_THEME),
			'logged_in' => __('Logged in', HS_CURRENT_THEME),
			'logged_in_as' => __('Logged in as', HS_CURRENT_THEME),
			'log_account' => __('Log out of this account;', HS_CURRENT_THEME),
			'log_out' => __('Log out &raquo;', HS_CURRENT_THEME),
			'name_comment' => __('Name', HS_CURRENT_THEME),
			'email_comment' => __('Email (will not be published)', HS_CURRENT_THEME),
			'website_comment' => __('Website', HS_CURRENT_THEME),
			'your_comment' => __('Your comment*', HS_CURRENT_THEME),
			'submit_comment' => __('Submit Comment', HS_CURRENT_THEME),
			
			//share-buttons.php
			'tweet_this_article' => __('Tweet this article', HS_CURRENT_THEME),
			
			//loop-archives.php
			'continue_reading' => __('Continue Reading', HS_CURRENT_THEME),
			'pages' => __('Pages:', HS_CURRENT_THEME),
			'last_posts' => __('Last 30 Posts', HS_CURRENT_THEME),
			'archives_month' => __('Archives by Month:', HS_CURRENT_THEME),
			'archives_subject' => __('Archives by Subject:', HS_CURRENT_THEME),
			
			//loop-author.php
			'about' => __('About:', HS_CURRENT_THEME),
			'recent_posts_by' => __('Recent Posts by', HS_CURRENT_THEME),
			'no_post_yet' => __('No post yet', HS_CURRENT_THEME),
			'recent_comments_by' => __('Recent Comments by', HS_CURRENT_THEME),
			'no_comments_author' => __('%1$s on %2$s', HS_CURRENT_THEME),
			'no_comments_by' => __('No comments by', HS_CURRENT_THEME),
			'yet' => __('yet.', HS_CURRENT_THEME),
			
			//loop-blog.php //loop-single-testi.php
			'there_has' => __('There has been an error.', HS_CURRENT_THEME),
			'we_apologize' => __('We apologize for any inconvenience, please', HS_CURRENT_THEME),
			'return_to' => __('return to the home page', HS_CURRENT_THEME),
			'search_form' => __('or use the search form below.', HS_CURRENT_THEME),
			
			//loop-faq.php
			'q' => __('Q?', HS_CURRENT_THEME),
			'a' => __('A.', HS_CURRENT_THEME),
			
			//loop-single.php
			'written_by' => __('Written by', HS_CURRENT_THEME),
			'view_all' => __('View all posts by', HS_CURRENT_THEME),
			
			//portfolio-loop.php
			'not_found' => __('Not Found', HS_CURRENT_THEME),
			'apologies' => __('Apologies, but no results were found for the requested archive. Perhaps searching will help find a related post.', HS_CURRENT_THEME),
			
			//static-footer-text.php
			'powered_by' => __('is proudly powered by', HS_CURRENT_THEME),
			'entries_rss' => __('Entries (RSS)', HS_CURRENT_THEME),
			'comments_rss' => __('Comments (RSS)', HS_CURRENT_THEME),
			'privacy_policy' => __('Privacy Policy', HS_CURRENT_THEME),
			
			//title.php
			'category_archives' => __('Category Archives', HS_CURRENT_THEME),
			'portfolio_category' => __('Portfolio Category', HS_CURRENT_THEME),
			'fearch_for' => __('Search for', HS_CURRENT_THEME),
			'posts_by_type' => __('Posts by type', HS_CURRENT_THEME),
			'daily_archives' => __('Daily Archives', HS_CURRENT_THEME),
			'monthly_archives' => __('Monthly Archives', HS_CURRENT_THEME),
			'yearly_archives' => __('Yearly Archives', HS_CURRENT_THEME),
			'by' => __('by ', HS_CURRENT_THEME),
			'tag_archives' => __('Tag Archives', HS_CURRENT_THEME),
			'portfolio_tag' => __('Portfolio Tag', HS_CURRENT_THEME),
			
			//header.php
			'category_for' => __('Category Archive for', HS_CURRENT_THEME),
			'tag_for' => __('Tag Archive for', HS_CURRENT_THEME),
			'archive' => __('Archive', HS_CURRENT_THEME),
			'error_404' => __('Error 404 Not Found', HS_CURRENT_THEME),
			
			//loop-single-portfolio.php
			'launch_project' => __('Launch Project', HS_CURRENT_THEME),
			
			//static-not-found.php
			'sorry' => __('Sorry!', HS_CURRENT_THEME),
			'page_not_found' => __('Page Not Found', HS_CURRENT_THEME),
			'page_you_are_looking' => __('The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.', HS_CURRENT_THEME),
			'please_try_using' => __('Please try using our search box below to look for information on the internet.', HS_CURRENT_THEME),
			
			//posts_list.php
			'posted_in' => __('Posted in', HS_CURRENT_THEME),

			//standard.php
			'featured' => __('Featured', HS_CURRENT_THEME),

			//Child theme
			//custom-function.php
			'submit_permalink' => __('Submit Permalink Structure', HS_CURRENT_THEME),
			'submit_permalink_desc' => __("This way of links configuration can be used by not only our blog followers but will help in SEO-optimisation as well. The effectiveness and main features of this link configuration method are revealed <a href='http://codex.wordpress.org/Using_Permalinks'>here</a>", HS_CURRENT_THEME),
			'import_sample_data' => __('Import Sample Data', HS_CURRENT_THEME),
			'import_sample_data_desc' => __('If you want to install sample data from livedemo you need to go to <strong>Options</strong> > <strong>Import</strong> and follow the tips.', HS_CURRENT_THEME),
			'import_sample_data_desc_2' => __('If you want to install sample data from livedemo you need to go to <strong>Import</strong> and follow the tips.', HS_CURRENT_THEME),
			
			//options-interface.php
			'no_lable' => __('No lable.', HS_CURRENT_THEME),

			//other
			'theme_options_media' => __('Theme Options Media', HS_CURRENT_THEME),

			//widgets-manager.php
			'visibility'            => __('Visibility', HS_CURRENT_THEME),
			'visible_at'            => __('Visible on', HS_CURRENT_THEME),
			'visible_on'            => __('Visible on', HS_CURRENT_THEME),
			'visible_for'           => __('Visible for', HS_CURRENT_THEME),
			'all_pages'             => __('Every page', HS_CURRENT_THEME),
			'all_pages_expecting'   => __('Every page except', HS_CURRENT_THEME),
			'no_pages_expecting'    => __('None of the pages except', HS_CURRENT_THEME),
			'homepage'              => __('Homepage', HS_CURRENT_THEME),
			'page'                  => __('Page', HS_CURRENT_THEME),
			'post'                  => __('Post', HS_CURRENT_THEME),
			'archive'               => __('Archive', HS_CURRENT_THEME),
			'page_template'         => __('Page Template', HS_CURRENT_THEME),
			'search_page'           => __('Search page', HS_CURRENT_THEME),
			'404_page'              => __('404 page', HS_CURRENT_THEME),
			'page_id_title_slug'    => __('Page ID/Title/slug', HS_CURRENT_THEME),
			'post_id_title_slug'    => __('Post ID/Title/slug', HS_CURRENT_THEME),
			'category_id_name_slug' => __('Category ID/Name/slug', HS_CURRENT_THEME),
			'tag_id_name'           => __('Tag ID/Name', HS_CURRENT_THEME),
			'template'              => __('Template', HS_CURRENT_THEME),
			'add_page'              => __('Add page', HS_CURRENT_THEME),
			'selected_pages'        => __('Selected pages', HS_CURRENT_THEME),
			'no_pages'              => __('No pages', HS_CURRENT_THEME),
			'all_devices'           => __('All devices', HS_CURRENT_THEME),
			'desktops'              => __('Desktops', HS_CURRENT_THEME),
			'tablets'               => __('Tablets', HS_CURRENT_THEME),
			'phones'                => __('Phones', HS_CURRENT_THEME),
			'desktops_tablets'      => __('Desktops/Tablets', HS_CURRENT_THEME),
			'tablets_phones'        => __('Tablets/Phones', HS_CURRENT_THEME),
			'desktops_phones'       => __('Desktops/Phones', HS_CURRENT_THEME),
			'all_users'             => __('All users', HS_CURRENT_THEME),
			'only_guests'           => __('Only guests', HS_CURRENT_THEME),
			'only_registered_users' => __('Only registered users', HS_CURRENT_THEME),
			'only_administrator'    => __('Only administrator', HS_CURRENT_THEME),
			'select_page_to_add'    => __('Select page to add', HS_CURRENT_THEME),
			'custom_css_class'      => __('Custom CSS class', HS_CURRENT_THEME),

			//seo_settings_page.php
			'sitemap_xml' => __('Sitemap XML', HS_CURRENT_THEME),
			'include_post_types' => __('Include post types.', HS_CURRENT_THEME),
			'priority' => __('Priority.', HS_CURRENT_THEME),
			'change_freq' => __('Change freq.', HS_CURRENT_THEME),
			'post_types_settings' => __('Post types settings.', HS_CURRENT_THEME),
			'include_post_types_desc' => __('<strong>Include post types</strong> - specify the post types which will be included into your sitemap.', HS_CURRENT_THEME),
			'priority_desc' => __('<strong>Priority</strong> - set post type priorities on your site. For example, if the blog page content is more important for search engines than the portfolio page content, set the priority for blog posts as 1, for portfolio pages as 0.9 and so on.', HS_CURRENT_THEME),
			'change_freq_desc' => __('<strong>Change frequency</strong> - specify how often you change certain post types. It helps the search engines to determine how relevant your information is at the moment of search.', HS_CURRENT_THEME),
			'ping_sitemap_desc' => __('<strong>Ping sitemap</strong> - choose the search engines which will receive the link to your sitemap.', HS_CURRENT_THEME),
			'ping_sitemap' => __('Ping sitemap.', HS_CURRENT_THEME),
			'seo' => __('SEO', HS_CURRENT_THEME),
			'index_settings' => __('Your website indexation settings.', HS_CURRENT_THEME),
			'forbid' => __('Forbid the search engines to index the following directories of your site.', HS_CURRENT_THEME),
			'these_settings' => __('These settings will help reduce the information search range on your site. ', HS_CURRENT_THEME),
			'admin_index' => __('WordPress engine system files and folders <em>(recommended)</em>', HS_CURRENT_THEME),
			'plagin_index' => __('Your plugins system files and folders <em>(recommended)</em>', HS_CURRENT_THEME),
			'theme_index' => __('Your themes system files and folders <em>(recommended)</em>', HS_CURRENT_THEME),
			'media_index' => __('Media library files (images, video, audio, etc.) <em>(not recommended)</em>', HS_CURRENT_THEME),
			'nofollow_name' => __('Add the <em>"rel"</em> attribute with the <em>"nofollow"</em> value to content links.', HS_CURRENT_THEME),
			'nofollow_desc' => __('This option will stop the search engines from going to other sites following the links in your site content.', HS_CURRENT_THEME)
			);
		return $locals[$label];
	};
?>